package com.metasequoia.services.mcu;

import android.os.IBinder;
import android.os.IInterface;

public interface ICustomCarSysInterface extends IInterface {
    int BIND_REGISTER_SYS = IBinder.FIRST_CALL_TRANSACTION;
    int BIND_UNREGISTER_SYS = IBinder.FIRST_CALL_TRANSACTION + 1;
    int BIND_SEND_SPEAKER = IBinder.FIRST_CALL_TRANSACTION + 2;//发送语音
    int BIND_SET_TOP_PACKAGE = IBinder.FIRST_CALL_TRANSACTION + 3;//设置当前前台应用
    int BIND_SET_NAV_STATE = IBinder.FIRST_CALL_TRANSACTION + 4;//设置导航打开状态
    int BIND_SET_BLE_STATE = IBinder.FIRST_CALL_TRANSACTION + 5;//设置蓝牙打开状态
    int BIND_SET_FM_STATE = IBinder.FIRST_CALL_TRANSACTION + 6;//设置FM打开状态
    int BIND_NOTIFY_ACC_STATUS = IBinder.FIRST_CALL_TRANSACTION + 7;//acc状态
    int BIND_NOTIFY_BAT_POWER = IBinder.FIRST_CALL_TRANSACTION + 8;//剩余电量
    int BIND_NOTIFY_BAT_STATE = IBinder.FIRST_CALL_TRANSACTION + 9;//电池状态
    int BIND_NOTIFY_CAR_GEAR = IBinder.FIRST_CALL_TRANSACTION + 10;//档位状态
    int BIND_NOTIFY_CAR_SPEED = IBinder.FIRST_CALL_TRANSACTION + 11;//车速
    int BIND_NOTIFY_ROTATE_SPEED = IBinder.FIRST_CALL_TRANSACTION + 12;//转速
    int BIND_NOTIFY_TOTAL_MIL = IBinder.FIRST_CALL_TRANSACTION + 13;//总里程
    int BIND_NOTIFY_REM_MIL = IBinder.FIRST_CALL_TRANSACTION + 14;//剩余里程
    int BIND_NOTIFY_WIFI_ACCOUNT = IBinder.FIRST_CALL_TRANSACTION + 15;//wifi账号
    int BIND_NOTIFY_WIFI_PWD = IBinder.FIRST_CALL_TRANSACTION + 16;//wifi密码

    int BIND_GET_ACC_STATUS = IBinder.FIRST_CALL_TRANSACTION + 17;//获取acc状态
    int BIND_GET_BAT_POWER = IBinder.FIRST_CALL_TRANSACTION + 18;//获取电池剩余电量
    int BIND_GET_BAT_STATE = IBinder.FIRST_CALL_TRANSACTION + 19; //获取电池状态
    int BIND_GET_CAR_GEAR = IBinder.FIRST_CALL_TRANSACTION + 20;//获取档位状态
    int BIND_GET_CAR_SPEED = IBinder.FIRST_CALL_TRANSACTION + 21;//获取车速
    int BIND_GET_ROTATE_SPEED = IBinder.FIRST_CALL_TRANSACTION + 22;//获取转速
    int BIND_GET_TOTAL_MIL = IBinder.FIRST_CALL_TRANSACTION + 23;//获取总里程
    int BIND_GET_REM_MIL = IBinder.FIRST_CALL_TRANSACTION + 24;//获取剩余里程
    int BIND_GET_WIFI_ACCOUNT = IBinder.FIRST_CALL_TRANSACTION + 25;//获取wifi账号
    int BIND_GET_WIFI_PWD = IBinder.FIRST_CALL_TRANSACTION + 26;//获取wifi密码
    int BIND_NOTIFY_KEY_EVENT = IBinder.FIRST_CALL_TRANSACTION + 27;//key事件通知
    int BIND_SET_FACE_STATE = IBinder.FIRST_CALL_TRANSACTION + 28;//人脸认证状态
    int BIND_SET_GRADING = IBinder.FIRST_CALL_TRANSACTION + 29;//设置评分等级
    int BIND_SET_DEST_PER_INFO = IBinder.FIRST_CALL_TRANSACTION + 30;//目的地周边优惠信息
    int BIND_SET_ORDER_INFO = IBinder.FIRST_CALL_TRANSACTION + 31;//订单信息

    int BIND_NOTIFY_DEV_ID = IBinder.FIRST_CALL_TRANSACTION + 32;//Tbox ID
    int BIND_GET_DEV_ID = IBinder.FIRST_CALL_TRANSACTION + 33; //获取Tbox ID

    int BIND_NOTIFY_BAT_VOLTAGE = IBinder.FIRST_CALL_TRANSACTION + 34;//小电瓶电压
    int BIND_GET_BAT_VOLTAGE = IBinder.FIRST_CALL_TRANSACTION + 35;//获取小电瓶电压
}
